name: fuzzy
version: 0.2.4

description: >
  Fuzzy search in Dart. initially translated from Fuse.js.
homepage: https://github.com/comigor/fuzzy

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  latinize: ^0.0.2
  meta: ^1.2.4

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.2
