name: fuzzy
<<<<<<< Updated upstream
version: 0.2.0+1
=======
<<<<<<< Updated upstream
version: 0.2.0
=======
version: 0.2.0+2
>>>>>>> Stashed changes
>>>>>>> Stashed changes

authors:
  - Igor Borges <igor@borges.dev>

description: >
  Fuzzy search in Dart. Basically a code conversion, subset of Fuse.js.
homepage: https://github.com/comigor/fuzzy
repository: https://github.com/comigor/fuzzy
issue_tracker: https://github.com/comigor/fuzzy/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  latinize: ^0.0.2

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.9.0
