on: [pull_request, push]

name: CI

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Clone repository
  #     uses: actions/checkout@master
  #   - name: Run tests
  #     uses: comigor/actions/dart-test@master
  check-version:
    # needs: test
    runs-on: ubuntu-latest
    container: golang
    steps:
    - name: Clone repository
      uses: actions/checkout@master
    - name: Check if version was changed and changelog updated
      run: |
        echo "----------------install"
        GO111MODULE=on go get github.com/mikefarah/yq/v2
        go get -u github.com/itchyny/gojq/cmd/gojq

        cd "$GITHUB_WORKSPACE"

        echo "----------------event"
        echo "$GITHUB_EVENT_PATH"
        gojq '.commits | length' "${GITHUB_EVENT_PATH}"
        echo "----------------files"
        ls
        echo "----------------diff"
        git diff HEAD~$(gojq '.commits | length' "${GITHUB_EVENT_PATH}") pubspec.yaml
        echo "----------------version"
        package_version=$(yq r pubspec.yaml version)
        echo "::set-env name=package_version::$package_version"
        echo "::warning::$package_version"
        echo "$package_version"
        echo "----------------changelog"
        cat CHANGELOG.md | grep $package_version
        exit 0
  deploy:
    needs: check-version
    runs-on: ubuntu-latest    
    if: contains(github.ref, 'master')
    steps:    
    - name: Clone repository
      uses: actions/checkout@master          
    - name: Publish to pub.dev
      uses: comigor/actions/pub-publish@master      
      env:
        PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
