on: [pull_request, push]

name: CI

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Clone repository
  #     uses: actions/checkout@master
  #   - name: Run tests
  #     uses: comigor/actions/dart-test@master
  check-version-and-changelog:
    # needs: test
    runs-on: ubuntu-latest
    container: golang
    steps:
    - name: Clone repository
      uses: actions/checkout@master
    - run: go get -u github.com/itchyny/gojq/cmd/gojq
    - name: Check if version on pubspec.yaml was changed
      run: |
        cd "$GITHUB_WORKSPACE"

        if test "${{ github.ref }}" = "master"; then
          diff=$(git diff HEAD~$(gojq '.commits | length' "${GITHUB_EVENT_PATH}") pubspec.yaml)
        else
          git fetch origin master:master
          diff=$(git diff origin/master pubspec.yaml)
        fi

        echo "$diff" | grep -E '\+.*version'
    - name: Check if there's an entry for this new version on CHANGELOG
      run: |
        cd "$GITHUB_WORKSPACE"

        package_version=$(cat pubspec.yaml | gojq --yaml-input -r '.version')
        cat CHANGELOG.md | grep $package_version
  deploy:
    needs: check-version-and-changelog
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
    - name: Clone repository
      uses: actions/checkout@master
    - name: Publish to pub.dev
      uses: comigor/actions/pub-publish@master
      env:
        PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
